version: 0.0.{build}
image: Visual Studio 2017
build_script:
  - ps: dotnet build
test_script:
  - ps: dotnet test
deploy:
  - provider: NuGet
    server: https://nuget.org
    skip_symbols: true
    on:
      branch: master
